# Generated by Django 2.2.1 on 2019-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190508_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='current_location',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_location',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
