# Generated by Django 2.2.1 on 2019-05-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190508_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='last_location',
        ),
    ]
