# Generated by Django 2.2.1 on 2019-05-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_last_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='current_location',
            new_name='name',
        ),
    ]
