# Generated by Django 2.2.1 on 2019-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='last_location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
