# Generated by Django 2.2.1 on 2019-05-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20190508_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipments', unique=True),
        ),
    ]
