# Generated by Django 2.2.1 on 2019-05-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('equipments', '0006_auto_20190509_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='patient.Patient'),
        ),
    ]
