# Generated by Django 2.2.1 on 2019-05-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_booked_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
