# Generated by Django 2.2.1 on 2019-05-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20190509_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.Patient'),
        ),
    ]
