# Generated by Django 2.2.1 on 2019-05-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_auto_20190509_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
