# Generated by Django 2.2.1 on 2019-05-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_auto_20190509_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.Patient'),
        ),
    ]
