# Generated by Django 2.2.1 on 2019-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_auto_20190509_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='motif',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
