# Generated by Django 2.2.1 on 2019-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_auto_20190509_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
