# Generated by Django 2.2.1 on 2019-05-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_auto_20190509_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='last_location',
        ),
    ]
