# Generated by Django 2.2.1 on 2019-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_remove_equipments_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='patient',
        ),
        migrations.AlterField(
            model_name='booked',
            name='end',
            field=models.DateField(auto_now=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
