# Generated by Django 2.2.1 on 2019-05-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_auto_20190530_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
