# Generated by Django 2.2.1 on 2019-05-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_auto_20190531_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='end',
            field=models.DateField(),
        ),
    ]
