# Generated by Django 2.2.1 on 2019-05-31 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_auto_20190531_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipments'),
        ),
    ]
