# Generated by Django 2.2.2 on 2019-06-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0021_auto_20190531_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='title',
            field=models.CharField(default='Aucune catégorie', max_length=100, unique=True),
        ),
    ]
