# Generated by Django 2.2.2 on 2019-06-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0022_auto_20190618_2110'),
        ('equipments', '0022_auto_20190618_2134'),
    ]

    operations = [
    ]
