# Generated by Django 2.2.2 on 2019-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0023_merge_20190618_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
